In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

In [16]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(digits.data,digits.target,test_size=0.3)

In [17]:
lr = LogisticRegression()
lr.fit(xtrain,ytrain)
lr.score(xtest,ytest)

C:\Users\lapin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\lapin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.9537037037037037

In [18]:
svm = SVC()
svm.fit(xtrain,ytrain)
svm.score(xtest,ytest)

C:\Users\lapin\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.30185185185185187

In [19]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(xtrain,ytrain)
rf.score(xtest,ytest)

0.9666666666666667

In [20]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

In [21]:
for trainindex,testindex in kf.split([1,2,3,4,5,6,7,8,9]):
    print(trainindex,testindex)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [22]:
def get_score(model,xtrain,xtest,ytrain,ytest):
    model.fit(xtrain,ytrain)
    return model.score(xtest,ytest)

In [23]:
get_score(LogisticRegression(),xtrain,xtest,ytrain,ytest)

C:\Users\lapin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\lapin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.9537037037037037

In [26]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [33]:
scores_l = []
scores_svm = []
scores_rf = []
for trainindex,testindex in kf.split(digits.data):
    xtrain,xtest,ytrain,ytest = digits.data[trainindex], digits.data[testindex], \
        digits.target[trainindex],digits.target[testindex]
    scores_l.append(get_score(LogisticRegression(),xtrain,xtest,ytrain,ytest))
    scores_svm.append(get_score(SVC(),xtrain,xtest,ytrain,ytest))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),xtrain,xtest,ytrain,ytest))
    

C:\Users\lapin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\lapin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\lapin\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\lapin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\lapin\Anaconda3\lib\site-packag

In [34]:
scores_l

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [35]:
scores_svm

[0.41068447412353926, 0.41569282136894825, 0.4273789649415693]

In [36]:
scores_rf

[0.9282136894824707, 0.9465776293823038, 0.9232053422370617]

In [37]:
from sklearn.model_selection import cross_val_score

In [39]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\lapin\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\lapin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\lapin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\lapin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\lapin\Anaconda3\lib\site-packages\sklearn\linear_model\logist

array([0.89534884, 0.94991653, 0.90939597])