In [2]:
import numpy as np

In [5]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
for cell in a.flatten():
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [13]:
for x in np.nditer(a,order="C"):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [15]:
for x in np.nditer(a,order="F",flags=["external_loop"]):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [16]:
for x in np.nditer(a,op_flags=["readwrite"]):
    x[...]=x*x

In [17]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [22]:
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [21]:
for x,y in np.nditer([a,b]):
    print(x,y)

SyntaxError: invalid syntax (<ipython-input-21-c75f45476bb7>, line 1)